- hosts: all
  tasks:

    - name: Update apt repository and distribution,and install packages  
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

            # - name: Download public signing key for kubernetes package repos
            # shell: |
            #  curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
            #  echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        
    - name: Install kubelet, kubeadm and kubectl, and pin their version
      apt:
        pkg: 
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Prevent Kubernetes packages from being upgraded
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl 
