- hosts: all
  tasks:

    - name: Update apt repository and distribution,and install packages  
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

    - name: Install kubelet, kubeadm and kubectl, and pin their version
      apt:
        pkg: 
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Prevent Kubernetes packages from being upgraded
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl 
